options(
    SKIP=1,
    PARALLEL=false,
    DIRECT=true,
    MULTITHREADING=true
)
LOAD DATA
CHARACTERSET UTF8
INFILE 'output.csv'
INSERT INTO TABLE PERSON2
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(
    PID sequence,
    VORNAME,
    NACHNAME,
    STRASSE,
    GO_PLZ,
    WO_PLZ,
    GEBURTSDATUM DATE "YYYY-mm-dd",
    GEBURTSORT,
    WOHNORT,
    HAUSNUMMER
)
